In [4]:
import pandas as pd
import numpy as np

In [5]:
import matplotlib.pyplot as mp


In [6]:
data=pd.read_csv("C:/Users/HEMANTH REDDY/Downloads/Health monitoring csv.csv")

In [7]:
data

SBP  DBP  Pulse  Temperature  Level
0    120   80     80           98      0
1    140   83     75          100      1
2    155  100     92          104      2
3    115   82     79           97      0
4    119   79     85          102      1
5     95   65     75          101      2
6    116   75     70           99      0
7    100   60     79           98      2
8    119   78     68          100      0
9    110   69     65          102      2
10   117   73     76           99      0
11   130   88     84          101      1
12   145   90     82          104      2
13   118   75     75           99      0
14   114   76     69           98      0
15   105   65     60          102      2
16   132   89     76          101      1
17   135   87     76          100      1
18   140   91     80          102      2
19   119   78     70           99      0
20   116   77     74           98      0
21   106   68     79          103      2
22   129   89     82          100      1
23   126   90     80          101      1
24   147   95     84          104      2
25   116   78     70           98      0
26   118   76     68           99      0
27   128   87     80          100      1
28   130   85     82          101      1
29   148   92     84          104      2
..   ...  ...    ...          ...    ...
119  119   80     73           99      0
120  119   79     70           98      0
121  125   85     75          100      1
122  126   87     77          101      1
123  128   88     79          101      1
124  130   85     76          100      1
125  148   90     76          101      2
126  147   92     80           99      2
127  153  101     81          102      2
128  151   99     82          103      2
129  118   78     68           98      0
130  119   79     70           98      0
131  120   78     71           99      0
132  119   78     74           98      0
133   98   64     76           98      2
134  104   67     84          103      2
135  106   62     78          102      2
136  130   87     76          100      1
137  116   78     73           98      0
138  118   79     69           98      0
139  117   77     74           98      0
140  134   86     78          100      1
141  136   87     80          101      1
142  139   88     81          100      1
143  147   94     79          100      2
144  154   99     83          103      2
145  118   77     73           98      0
146  125   87     79          102      1
147  132   88     78          101      1
148  118   82     74           98      0

[149 rows x 5 columns]

In [8]:
data.isnull().values.any()

False

In [9]:
x = data.iloc[:, :4].values  
y = data.iloc[:, 4].values

In [10]:
x

array([[120,  80,  80,  98],
       [140,  83,  75, 100],
       [155, 100,  92, 104],
       [115,  82,  79,  97],
       [119,  79,  85, 102],
       [ 95,  65,  75, 101],
       [116,  75,  70,  99],
       [100,  60,  79,  98],
       [119,  78,  68, 100],
       [110,  69,  65, 102],
       [117,  73,  76,  99],
       [130,  88,  84, 101],
       [145,  90,  82, 104],
       [118,  75,  75,  99],
       [114,  76,  69,  98],
       [105,  65,  60, 102],
       [132,  89,  76, 101],
       [135,  87,  76, 100],
       [140,  91,  80, 102],
       [119,  78,  70,  99],
       [116,  77,  74,  98],
       [106,  68,  79, 103],
       [129,  89,  82, 100],
       [126,  90,  80, 101],
       [147,  95,  84, 104],
       [116,  78,  70,  98],
       [118,  76,  68,  99],
       [128,  87,  80, 100],
       [130,  85,  82, 101],
       [148,  92,  84, 104],
       [100,  65,  62,  95],
       [ 99,  60,  65,  94],
       [119,  78,  74,  98],
       [117,  79,  76,  99],
       [116,  

In [11]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20,random_state=0)  

In [12]:
x_train

array([[128,  87,  80, 100],
       [ 99,  66,  79, 102],
       [107,  65,  80, 102],
       [ 98,  60,  64, 101],
       [140,  91,  80, 102],
       [136,  90,  79, 101],
       [130,  87,  76, 100],
       [118,  81,  72,  98],
       [140,  99,  85, 102],
       [155, 100,  92, 104],
       [125,  87,  79, 102],
       [117,  73,  76,  99],
       [104,  68,  79, 101],
       [154,  99,  79, 100],
       [147,  94,  79, 100],
       [120,  78,  69,  98],
       [128,  86,  64, 101],
       [104,  68,  79, 101],
       [126,  85,  76, 100],
       [120,  78,  71,  99],
       [119,  79,  70,  98],
       [120,  80,  76,  98],
       [118,  77,  73,  98],
       [132,  87,  77,  98],
       [118,  79,  76, 100],
       [147,  92,  80,  99],
       [127,  84,  75, 100],
       [100,  65,  62,  95],
       [119,  80,  75,  98],
       [118,  76,  74,  98],
       [117,  80,  73,  99],
       [151,  95,  80, 100],
       [128,  88,  79, 101],
       [118,  79,  73,  99],
       [126,  

In [13]:
x_test

array([[ 98,  64,  76,  98],
       [145, 100,  75, 100],
       [126,  85,  79,  99],
       [100,  63,  80, 103],
       [100,  60,  79,  98],
       [135,  89,  80, 100],
       [134,  86,  78, 100],
       [117,  60,  85, 100],
       [116,  80,  70,  98],
       [115,  78,  70,  98],
       [117,  79,  76,  99],
       [117,  78,  75,  98],
       [119,  78,  70,  98],
       [147,  95,  84, 104],
       [127,  89,  80,  98],
       [119,  78,  74,  98],
       [146,  95,  81, 100],
       [128,  88,  77,  99],
       [132,  89,  76, 101],
       [145,  92,  82, 101],
       [118,  79,  76, 106],
       [119,  78,  68, 100],
       [150,  96,  82, 102],
       [129,  89,  82, 100],
       [120,  78,  70,  99],
       [120,  80,  75, 105],
       [119,  78,  70,  98],
       [118,  76,  68,  99],
       [118,  79,  70,  99],
       [104,  67,  84, 103]], dtype=int64)

In [16]:
from sklearn.neighbors import KNeighborsClassifier  
classifier = KNeighborsClassifier(n_neighbors=5)  
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [17]:
y_pred = classifier.predict(x_test) 

In [18]:
y_pred

array([2, 2, 1, 2, 2, 1, 1, 2, 0, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 2, 0, 0,
       2, 1, 0, 0, 0, 0, 0, 2], dtype=int64)

In [19]:
y_test

array([2, 2, 1, 2, 2, 1, 1, 1, 0, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 2, 2, 0,
       2, 1, 0, 2, 0, 0, 0, 2], dtype=int64)

In [21]:
 y_pred = classifier.predict([ [118,  78,  69,  104]]) 

In [22]:
y_pred

array([0], dtype=int64)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

[[11  0  0]
 [ 0  7  1]
 [ 2  0  9]]
              precision    recall  f1-score   support

           0       0.85      1.00      0.92        11
           1       1.00      0.88      0.93         8
           2       0.90      0.82      0.86        11

   micro avg       0.90      0.90      0.90        30
   macro avg       0.92      0.90      0.90        30
weighted avg       0.91      0.90      0.90        30

